apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
  labels:
    app: myblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      - name: myblog
        image: roboghost/test1-myblog:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: ClusterIP
  selector:
    component: myblog
  ports:
    - port: 3000
      targetPort: 3000

