apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
  labels:
    app: myblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      - name: myblog
        image: roboghost/test1-myblog:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myblog-service
  labels:
    app: myblog
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: myblog
  selector:
    app: myblog
  type: LoadBalancer
